import {
  BookOpen,
  BrainCircuit,
  CreditCard,
  HelpCircle,
  Lock,
  Settings,
} from "lucide-react";

export const faqContent = {
  hero: {
    badge: "Help Center",
    title: "Frequently Asked Questions",
    description:
      "Find answers to the most common questions about MindPlanAI, your account, AI features, billing and security.",
  },

  categories: [
    {
      id: "general",
      title: "General",
      icon: HelpCircle,
    },
    {
      id: "ai",
      title: "AI Features",
      icon: BrainCircuit,
    },
    {
      id: "account",
      title: "Account",
      icon: Settings,
    },
    {
      id: "billing",
      title: "Billing",
      icon: CreditCard,
    },
    {
      id: "security",
      title: "Security",
      icon: Lock,
    },
    {
      id: "learning",
      title: "Learning",
      icon: BookOpen,
    },
  ],

  faqs: [
    {
      question: "What is MindPlanAI?",
      answer:
        "MindPlanAI is an AI-powered productivity platform that helps you create notes, generate learning roadmaps, summarize content, create quizzes and organize your learning efficiently.",
    },
    {
      question: "Do I need AI experience to use it?",
      answer:
        "No. MindPlanAI is designed for beginners as well as professionals with an intuitive and easy-to-use interface.",
    },
    {
      question: "Can I edit AI-generated notes?",
      answer:
        "Yes. Every note generated by AI can be edited, updated and saved anytime.",
    },
    {
      question: "Is my data secure?",
      answer:
        "Yes. Your notes and personal information are protected using secure authentication and encrypted communication.",
    },
    {
      question: "Can I cancel my subscription?",
      answer:
        "Yes. You can upgrade, downgrade or cancel your subscription whenever you want.",
    },
    {
      question: "Does MindPlanAI work on mobile devices?",
      answer:
        "Yes. The platform is fully responsive and works across desktop, tablet and mobile devices.",
    },
  ],

  cta: {
    badge: "Still Need Help?",
    title: "Couldn't Find Your Answer?",
    description:
      "Our support team is always ready to help you with any questions.",
    primaryButton: "Contact Support",
    secondaryButton: "Contact Us",
    icon: HelpCircle,
  },
};